### ISSUE TITLE
[FTR] Add who watched story

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#781] opened 2021-03-12 16:22 UTC
It would be nice if user could see who watched his story as in the original version of the client, as well as implement the notification function if the new user looked through the story (with the ability to enable / disable in the setting) 

P.S Thanks to the developers for the application

**Comment by austinhuang0131** [comment] 2021-03-13 18:59
Duplicate of #505

**Closed by austinhuang0131** 2021-03-13 18:59 UTC
Labels: enhancement
