### ISSUE TITLE
[BUG] crash on url opening

### ISSUE THREAD

**Issue by 532910** [austinhuang0131/barinsta#310] opened 2020-11-20 11:22 UTC
```
java.lang.NullPointerException: Attempt to invoke virtual method 'awais.instagrabber.models.ProfileModel awais.instagrabber.models.FeedModel.getProfileModel()' on a null object reference
        at awais.instagrabber.fragments.PostViewV2Fragment.setupProfilePic(PostViewV2Fragment.java:629)
        at awais.instagrabber.fragments.PostViewV2Fragment.init(PostViewV2Fragment.java:408)
        at awais.instagrabber.fragments.PostViewV2Fragment.onViewCreated(PostViewV2Fragment.java:251)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

v19.0.1
android 10

**Comment by austinhuang0131** [comment] 2020-11-23 03:49
Duplicate of #293, though you said "crash on url opening" but second row said `setupProfilePic` so like are you trying to open a post from a URL?

**Closed** 2020-11-30 17:30 UTC
Labels: bug, duplicate

**Comment by 532910** [comment] 2020-11-30 17:52
> are you trying to open a post from a URL?

Yep, I meant this under "crash on url opening".
Nice to hear that this has been fixed. Thank you!
