### ISSUE TITLE
[BUG] crash when tried to view saved

### ISSUE THREAD

**Issue by NSTAdventure** [austinhuang0131/barinsta#1749] opened 2021-07-25 02:03 UTC
- [ ✓] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [ ✓] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq.html).

app crash when try to see saved post

## Environment

 - Device: Realme 5i
 - Android version: 10

## Additional info
Either you or this app are very adorable :)

java:22760)
	at android.view.ViewGroup.layout(ViewGroup.java:6420)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1845)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22760)
	at android.view.ViewGroup.layout(ViewGroup.java:6420)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:833)
	at android.view.View.layout(View.java:22760)
	at android.view.ViewGroup.layout(ViewGroup.java:6420)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3519)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2930)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2037)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8402)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
	at android.view.Choreographer.doCallbacks(Choreographer.java:913)
	at android.view.Choreographer.doFrame(Choreographer.java:840)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1075)
	at android.os.Handler.handleCallback(Handler.java:899)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7853)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

*** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-07-25 03:52
> Either you or this app are very adorable :)

You mean both/and (either/or = 1 of 2, both/and = 2 of 2).

Your crash dump is also incomplete.

Duplicate of #1688 probably

**Closed by austinhuang0131** 2021-07-25 03:52 UTC
Labels: bug

**Comment by NSTAdventure** [comment] 2021-07-25 20:49
> Your crash dump is also incomplete.

1. Do not close this issues instantly pls
2. Idk it's produced directly from your app so what i can do is just send the report here

**Comment by austinhuang0131** [comment] 2021-07-25 20:53
1. It's closed because it's duplicate and fixed in code
2. If you sent it to Telegram then sent it here, then the crash dump will be cut into several segments, so you probably only sent the last segment. Note that emailing directly will always send the complete crash report.

**Comment by NSTAdventure** [comment] 2021-07-25 20:59
@austinhuang0131 



> 2\. If you sent it to Telegram then sent it here, then the crash dump will be cut into several segments, so you probably only sent the last segment. Note that emailing directly will always send the complete crash report (you can see other issues).

Fixed :)

**Comment by austinhuang0131** [comment] 2021-07-25 21:02
Okay, so it's still a duplicate of #1688

**Comment by NSTAdventure** [comment] 2021-07-25 21:07
> Okay, so it's still a duplicate of #1688

Nyu when you will release new version with this fix?

**Comment by austinhuang0131** [comment] 2021-07-25 21:09
somewhen, hopefully in 1 or 2 weeks, we don't do hotfixes unless it's absolutely necessary

**Comment by NSTAdventure** [comment] 2021-07-25 21:11
> somewhen, hopefully in 1 or 2 weeks, we don't do hotfixes unless it's absolutely necessary

Nyu thanks 😚
