### ISSUE TITLE
[FTR] Use without login

### ISSUE THREAD

**Issue by nikhilCad** [austinhuang0131/barinsta#954] opened 2021-04-03 13:30 UTC
**Is your feature request related to a problem? Please describe.**
The problem is that there is a tiny tiny chnce of account being banned

**Describe the solution you'd like**
In Newpipe, you can subscribe to channels without login. Similar things can be done for this app. Keep a local subscription list and show their collective post in chronological order

**Additional context**
None I guess

**Comment by nikhilCad** [comment] 2021-04-03 14:17
Okay I think there is a thing called Favourites

**Comment by nikhilCad** [comment] 2021-04-03 14:26
Okay the favourites just sit there and nothing changes. How do I get a collective feed without login?

**Comment by austinhuang0131** [comment] 2021-04-03 14:26
Duplicate of #24

**Closed by austinhuang0131** 2021-04-03 14:26 UTC
Labels: enhancement
