### ISSUE TITLE
App crashing on first select folder screen

### ISSUE THREAD

**Issue by FadeDave77** [austinhuang0131/barinsta#1762] opened 2021-07-25 16:37 UTC
Downloaded the app from fdroid, clicked on the select folder button, app crashed. Tried re-enabling the google files app, still didnt work. Tried restarting the phone, still no luck. The open document tree intent maybe should ask what activity I want it to use ;)

Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-25T19:14:02.453

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: N20Pro
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: DOOGEE
MANUFACTURER	: DOOGEE
BOARD			: v930
DEVICE			: N20Pro
PRODUCT		: N20Pro_EEA
HOST			: v119-R730xd
TAGS			: release-keys

Stack:
==============
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5192)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5150)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at awais.instagrabber.activities.-$$Lambda$DirectorySelectActivity$0hRDDTqoiGGyn-qTGVeQdFzORJU.onClick(lambda:3)
	at android.view.View.performClick(View.java:7146)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7119)
	at android.view.View.access$3500(View.java:803)
	at android.view.View$PerformClick.run(View.java:27533)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

Cause:
==============

**** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-07-25 16:50
Duplicate of #1467 

You need the Android file manager (`DocumentsUI`) which should be installed on your system already.

**Closed by austinhuang0131** 2021-07-25 16:50 UTC

**Comment by FadeDave77** [comment] 2021-07-25 17:04
It infact is not installed on my system. No app should hard depend on documentsui to be honest, as users of custom roms will probably not have it installed.

**Comment by austinhuang0131** [comment] 2021-07-25 17:06
Android OS in general hard depends on it and I really doubt there exists third-party file managers that support it

**Comment by FadeDave77** [comment] 2021-07-25 17:14
Well I use Material Files (me.zhanghai.android.files) as my file manager and until now every single app could use it's file selector, for example a pdf viewer asked me first time what application I would like to use as my file selector.

**Comment by austinhuang0131** [comment] 2021-07-25 17:22
You should contact them about it, though it does seem like the author is considering it.

**Comment by FadeDave77** [comment] 2021-07-25 17:31
Well, for now I will try to snatch a documentsui apk from somewhere and install it. Thanks for your help.
