### ISSUE TITLE
[FTR] Textcolor of hashtags and mentions

### ISSUE THREAD

**Issue by pred2k** [austinhuang0131/barinsta#613] opened 2021-01-18 12:44 UTC
Hi, i've discovered barinsta today and like it, thanks for the work!

The red colored hashtags and mentions are aggressive highlights for me :-) I think a slightly different color to the normal text would be enough to recognize these clickable words.

Thanks

**Comment by austinhuang0131** [comment] 2021-01-19 03:13
Duplicate of #448

**Closed by austinhuang0131** 2021-01-19 03:13 UTC
Labels: enhancement
