### ISSUE TITLE
Anonymous Saved and Liked

### ISSUE THREAD

**Issue by Github-com-foss** [austinhuang0131/barinsta#1414] opened 2021-06-11 06:25 UTC
Pls add saved and liked photos anonymously that not reflect in Account Like implement like Add to Favourites.
The saved ( bookmark and liked photos and videos) links that connect to internet Show results.

**Comment by austinhuang0131** [comment] 2021-06-11 13:23
Duplicate of #290

**Closed by austinhuang0131** 2021-06-11 13:23 UTC
Labels: enhancement
