### ISSUE TITLE
[FTR] Custom @mentions and links colour

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1038] opened 2021-04-11 13:59 UTC
I would like to have an option to set custom link / mention tag colour.

Currently it's red, which I would like to change to some other colour, because red seems too intrusive to me (like it's an error message or something).

**Comment by austinhuang0131** [comment] 2021-04-11 14:05
Duplicate of #448

**Closed by austinhuang0131** 2021-04-11 14:05 UTC
Labels: enhancement
