### ISSUE TITLE
[FTR] Version 19.2.0's navigation bar is a usability design regression

### ISSUE THREAD

**Issue by adamzea** [austinhuang0131/barinsta#1002] opened 2021-04-08 13:32 UTC
In version 19.2.0, the navigation bar labels have been removed and only show on the active tab. This is a regression in usability since new users will not immediately understand the ambiguous icons. Many studies (see below) show that user interaction increases when navigation elements are easy to understand. This is the "easy to learn" aspect of usability design. The best way to do this is to label them in a language the user understands. Users generally don't speak in cryptic icons.  
Ideally, the navigation should be instantly obvious by default, however, it's also ideal to give power-users the option to customize the navigation bar (remove labels, rearrange buttons) in order to increase the "easy to use" aspects.

Also see:
https://www.nngroup.com/videos/icon-text-labels/
https://blogs.msdn.microsoft.com/jensenh/2005/11/01/the-importance-of-labels/
https://thomasbyttebier.be/blog/the-best-icon-is-a-text-label
https://www.nngroup.com/articles/icon-usability/
https://uxdesign.cc/do-icons-need-labels-6cb4f4282c00
https://medium.com/google-design/the-obvious-ui-is-often-the-best-ui-7a25597d79fd

**Comment by austinhuang0131** [comment] 2021-07-11 18:44
Duplicate of #965

**Closed by austinhuang0131** 2021-07-11 18:44 UTC
Labels: enhancement
