### ISSUE TITLE
[BUG] Menu Bar  Profile or Personal Message open earlier 

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#784] opened 2021-03-12 17:36 UTC
If you open for example (profile) After that, go from the profile to subscribers and open another profile, we will be on another user profile, but when I select Open profile in the bottom menu, then I will not be see the page of my profile, i see profile of one who opened before .

I do not know maybe it is not a bug and feature)
On the one hand it is convenient, I can go back where I started, but on the other hand I would like to see functional the button to what it is intended for its profile or personal message.

## Suggest
if the user clicks 1 time on the button, show the page on which it was earlier, (example open profile)
if the user presses the 2nd time on the same button (the program checks and if the user does not go where the button sends the button) Then opens the profile page or personal messages

## Example
user open personal message  and open user profile in message list (now page show user profile)
user change menu to Feed
user again click in menu to Personal message (now see open user profile earlier
user presses the 2nd time on the same button Personal Message (now open Personal Message)

## Environment
    Device: 19.0.5 (57)
    Android version: 5.1
    
P.S Thanks to the developers for the application

**Comment by austinhuang0131** [comment] 2021-04-02 17:19
Duplicate of parts of #458 and you need to up your English a bit.

**Closed by austinhuang0131** 2021-04-02 17:19 UTC
Labels: bug
