### ISSUE TITLE
[FTR]Send Post

### ISSUE THREAD

**Issue by sonuu26** [austinhuang0131/barinsta#1118] opened 2021-04-17 10:21 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to share link of a post to someone, please add send post option

**Describe the solution you'd like**
Add share post option whenever I open a post

**Additional context**

**Comment by austinhuang0131** [comment] 2021-04-17 13:24
Duplicate of #537

**Closed by austinhuang0131** 2021-04-17 13:24 UTC
Labels: enhancement
