### ISSUE TITLE
[BUG] Crash upon selecting folder

### ISSUE THREAD

**Issue by cavebob** [austinhuang0131/barinsta#1615] opened 2021-07-10 06:48 UTC
### Steps to reproduce:
* Fresh install of app
* Open app
* App will request folder to be selected
* Upon pressing 'Select Folder' it will crash

I also manually set permissions just in case but it also crashed in the same way.
------

```
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-10T08:20:10.286

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: SM-G950F
ANDROID_VERS	: 11
ANDROID_REL	: 30
BRAND			: samsung
MANUFACTURER	: samsung
BOARD			: universal8895
DEVICE			: dreamlte
PRODUCT		: dreamltexx
HOST			: bldsrv
TAGS			: release-keys

Stack:
==============
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at awais.instagrabber.activities.-$$Lambda$DirectorySelectActivity$0hRDDTqoiGGyn-qTGVeQdFzORJU.onClick(lambda:3)
	at android.view.View.performClick(View.java:7455)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28313)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Cause:
==============

**** End of current Report ***
```

```
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-10T08:22:19.223

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: SM-G950F
ANDROID_VERS	: 11
ANDROID_REL	: 30
BRAND			: samsung
MANUFACTURER	: samsung
BOARD			: universal8895
DEVICE			: dreamlte
PRODUCT		: dreamltexx
HOST			: bldsrv
TAGS			: release-keys

Stack:
==============
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at awais.instagrabber.activities.-$$Lambda$DirectorySelectActivity$0hRDDTqoiGGyn-qTGVeQdFzORJU.onClick(lambda:3)
	at android.view.View.performClick(View.java:7455)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28313)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Cause:
==============

**** End of current Report ***
```
```
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-08T18:13:41.684

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: SM-G950F
ANDROID_VERS	: 11
ANDROID_REL	: 30
BRAND			: samsung
MANUFACTURER	: samsung
BOARD			: universal8895
DEVICE			: dreamlte
PRODUCT		: dreamltexx
HOST			: bldsrv
TAGS			: release-keys

Stack:
==============
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at awais.instagrabber.activities.-$$Lambda$DirectorySelectActivity$0hRDDTqoiGGyn-qTGVeQdFzORJU.onClick(lambda:3)
	at android.view.View.performClick(View.java:7455)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28313)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Cause:
==============

**** End of current Report ***
```
```
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-08T13:05:08.062

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: SM-G950F
ANDROID_VERS	: 11
ANDROID_REL	: 30
BRAND			: samsung
MANUFACTURER	: samsung
BOARD			: universal8895
DEVICE			: dreamlte
PRODUCT		: dreamltexx
HOST			: bldsrv
TAGS			: release-keys

Stack:
==============
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at awais.instagrabber.activities.-$$Lambda$DirectorySelectActivity$0hRDDTqoiGGyn-qTGVeQdFzORJU.onClick(lambda:3)
	at android.view.View.performClick(View.java:7455)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28313)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Cause:
==============

**** End of current Report ***
```
```
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-09T09:20:45.589

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: SM-G950F
ANDROID_VERS	: 11
ANDROID_REL	: 30
BRAND			: samsung
MANUFACTURER	: samsung
BOARD			: universal8895
DEVICE			: dreamlte
PRODUCT		: dreamltexx
HOST			: bldsrv
TAGS			: release-keys

Stack:
==============
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at awais.instagrabber.activities.-$$Lambda$DirectorySelectActivity$0hRDDTqoiGGyn-qTGVeQdFzORJU.onClick(lambda:3)
	at android.view.View.performClick(View.java:7455)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28313)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Cause:
==============

**** End of current Report ***

```
![Screenshot_20210710-084042_Shady_Launcher](https://user-images.githubusercontent.com/75441692/125154683-779d4080-e15b-11eb-9ebf-7a90e04c3711.png)
![Screenshot_20210710-084055_Shady_Launcher](https://user-images.githubusercontent.com/75441692/125154687-7d932180-e15b-11eb-926b-8482705f3e20.png)
![Screenshot_20210710-085405_Shady_Launcher](https://user-images.githubusercontent.com/75441692/125154860-7882a200-e15c-11eb-9989-fce220b13b6d.png)

**Comment by austinhuang0131** [comment] 2021-07-10 14:00
Duplicate of #1467 

Your device lacks DocumentsUI, which is included in the system's file manager. Please reenable it or reinstall it if you somehow changed it by root.

**Closed by austinhuang0131** 2021-07-10 14:00 UTC
Labels: bug

**Comment by cavebob** [comment] 2021-07-10 18:35
> Duplicate of #1467
> 
> Your device lacks DocumentsUI, which is included in the system's file manager. Please reenable it or reinstall it if you somehow changed it by root. Read storage permission not required and will be eventually removed.

Thanks, I didnt know the app depended on documents.ui. 

I've re-enabled it and the app now works as expected 👍
