### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by yant0** [austinhuang0131/barinsta#1584] opened 2021-07-07 05:16 UTC
New Trace collected:
=====================

Error report collected on: 2021-07-07T12:13:53.877

Information:
==============
VERSION	: 19.2.3-github_release
VERSION_CODE	: 64
PHONE-MODEL	: ASUS_X00TD
ANDROID_VERS	: 9
ANDROID_REL	: 28
BRAND	: asus
MANUFACTURER	: asus
BOARD	: sdm660
DEVICE	: ASUS_X00T_2
PRODUCT	: WW_X00TD
HOST	: 8846c848df6f
TAGS	: release-keys

Stack:
==============
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.austinhuang.instagrabber/awais.instagrabber.activities.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6692)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
at awais.instagrabber.fragments.PostViewV2Fragment.onCreate(PostViewV2Fragment.java:9)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:11)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:29)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:73)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:5)
at androidx.fragment.app.Fragment.onCreate(Fragment.java:4)
at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:45)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:11)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:29)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:75)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:5)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:4)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:4)
at awais.instagrabber.activities.BaseLanguageActivity.onCreate(BaseLanguageActivity.kt:9)
at awais.instagrabber.activities.MainActivity.onCreate(MainActivity.kt:3)
at android.app.Activity.performCreate(Activity.java:7140)
at android.app.Activity.performCreate(Activity.java:7131)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
... 11 more

Cause:
==============java.lang.RuntimeException: Unable to start activity ComponentInfo{me.austinhuang.instagrabber/awais.instagrabber.activities.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6692)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
at awais.instagrabber.fragments.PostViewV2Fragment.onCreate(PostViewV2Fragment.java:9)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:11)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:29)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:73)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:5)
at androidx.fragment.app.Fragment.onCreate(Fragment.java:4)
at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:45)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:11)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:29)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:75)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:5)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:4)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:4)
at awais.instagrabber.activities.BaseLanguageActivity.onCreate(BaseLanguageActivity.kt:9)
at awais.instagrabber.activities.MainActivity.onCreate(MainActivity.kt:3)
at android.app.Activity.performCreate(Activity.java:7140)
at android.app.Activity.performCreate(Activity.java:7131)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
... 11 more
kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
at awais.instagrabber.fragments.PostViewV2Fragment.onCreate(PostViewV2Fragment.java:9)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:11)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:29)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:73)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:5)
at androidx.fragment.app.Fragment.onCreate(Fragment.java:4)
at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:45)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:11)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:29)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:75)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:5)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:4)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:4)
at awais.instagrabber.activities.BaseLanguageActivity.onCreate(BaseLanguageActivity.kt:9)
at awais.instagrabber.activities.MainActivity.onCreate(MainActivity.kt:3)
at android.app.Activity.performCreate(Activity.java:7140)
at android.app.Activity.performCreate(Activity.java:7131)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6692)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**** End of current Report ***

Crash at opening app

**Comment by austinhuang0131** [comment] 2021-07-07 12:10
Duplicate of #1457

**Closed by austinhuang0131** 2021-07-07 12:10 UTC
Labels: bug
