### ISSUE TITLE
Double quotation marks in comments prevent sending comments

### ISSUE THREAD

**Issue by polynomialdonut** [austinhuang0131/barinsta#521] opened 2021-01-04 05:50 UTC
As stated in the title, comments with text containing quotation marks cannot be sent. A message pops up: "Unknown error occurred".

Reproduceable by sending any comment containing a quote in double quotes.

Seems like the string is directly parsed by a function that recognizes some special characters.
 
This is problematic,  I just verified that backslashes are parsed as an escape character, if I cancel the doubpe quotes as `\"`, then there is no problem with sending the comment. Backslashes also disappear, as is the case with escape characters normally.

Version `19.0.3 (55)` running on an Android 9 based ROM.

**Comment by austinhuang0131** [comment] 2021-01-04 15:13
fixed in 19.0.4 already

Duplicate of #453

**Closed by austinhuang0131** 2021-01-04 15:13 UTC
