### ISSUE TITLE
[BUG] Voice messages do not work

### ISSUE THREAD

**Issue by sigaloid** [austinhuang0131/barinsta#632] opened 2021-01-25 14:13 UTC
- [X] My app is on the latest version. I understand that any other version is not supported.
- [X] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Steps

1. Receive voice message
2. Press play
3. No audio

## Environment

 - Device: LG G7 ThinQ
 - Android version: Android 9

## Additional info

Not sure if a log would be helpful. Doesn't work across different devices, log out/in, etc. I can send you an empty voice message to test it out.

**Comment by austinhuang0131** [comment] 2021-01-25 14:26
Duplicate of #79

**Closed by austinhuang0131** 2021-01-25 14:26 UTC
Labels: bug

**Comment by sigaloid** [comment] 2021-01-25 14:32
You said it was a bug, so reply with a screenshot in #79. Though I didn't see the PR #503, is that what it is working on?

**Comment by sigaloid** [comment] 2021-01-25 14:35
Gotcha, thanks!
