### ISSUE TITLE
[FTR] Basic Post and Story functionality

### ISSUE THREAD

**Issue by tuxPT** [austinhuang0131/barinsta#336] opened 2020-11-24 23:57 UTC
Can you add basic post and story functionality? images and description should be enough. I'm trying to use as full client but if I can't post anything I need Instagram installed. Is it some api related limitation or time related?

**Comment by austinhuang0131** [comment] 2020-11-25 00:02
time & effort

duplicate of #201

**Closed by austinhuang0131** 2020-11-25 00:02 UTC
Labels: duplicate, enhancement
