### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by overtube** [austinhuang0131/barinsta#569] opened 2021-01-08 05:46 UTC
Hi, after update barinsta don't view messages, refresh and delete all app data and reinstalling wiil do not help.
![Screenshot_20210108-074114](https://user-images.githubusercontent.com/15115920/103978887-3795da80-5185-11eb-9fb1-3961492e51af.png)

**Comment by austinhuang0131** [comment] 2021-01-08 14:57
Duplicate of #444

**Closed by austinhuang0131** 2021-01-08 14:57 UTC
Labels: bug
