### ISSUE TITLE
[Bug] Crash Report - open hastag or account page without account 

### ISSUE THREAD

**Issue by abesty** [austinhuang0131/barinsta#1017] opened 2021-04-09 03:01 UTC
- [x] My apps is in the latest version
- [x] i have read the FAQ

- Barinsta crash when open a new page e.g either hastag or people account without login
- but it doesn't crash when open either hastag or account had been favorite before

Steps
1. Open barinsta
1. Click at search bar and write some new hastag or people account
1. open accou
1. crash

Environment
- device : samsung m21
- android version : 11

**Comment by austinhuang0131** [comment] 2021-04-09 03:02
Duplicate of #993

**Closed by austinhuang0131** 2021-04-09 03:02 UTC
