### ISSUE TITLE
[BUG] Add to favorites gone

### ISSUE THREAD

**Issue by mpern** [austinhuang0131/barinsta#1436] opened 2021-06-18 18:07 UTC
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Steps

1. Open Barinsta
1. Search for a profile
2. Try to add to favorites
3. ???

## Environment

 - Device: OnePlus 6T
 - Android version: LineageOS 18.1
 - Barinsta 19.2.2-fdroid (63)

## Additional info

I use Barinsta anonymously

**Comment by austinhuang0131** [comment] 2021-06-18 18:09
Duplicate of #1300

**Closed by austinhuang0131** 2021-06-18 18:09 UTC
Labels: bug
