### ISSUE TITLE
[FTR] DM visual enhancement – darker colour in dark theme

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1147] opened 2021-04-22 10:50 UTC
This is really just a minor tweak but I think the chat bubble here would look better with a bit darker colour:
![20210422_124221](https://user-images.githubusercontent.com/35201200/115702099-cb706880-a368-11eb-898f-3392b19eef49.jpg)
For example like this:
![20210422_124248](https://user-images.githubusercontent.com/35201200/115702242-f9ee4380-a368-11eb-8c35-5a35a6540e6b.jpg)
(This specific colour is hex #303030)

**Comment by austinhuang0131** [comment] 2021-04-22 12:31
Duplicate of #448

**Closed by austinhuang0131** 2021-04-22 12:31 UTC
Labels: enhancement

**Comment by Martin5001** [comment] 2021-04-22 15:40
Oh, sorry for the duplicate :) Didn't realize this would be covered by that.
