### ISSUE TITLE
[FTR] User Lists akin to Twitter

### ISSUE THREAD

**Issue by lvctr** [austinhuang0131/barinsta#1429] opened 2021-06-16 01:57 UTC
**Is your feature request related to a problem? Please describe.**
Instagram currently has an inconvenience where you are unable to group followed users together into various lists to view multiple feeds akin to Twitter.

**Describe the solution you'd like**
An editable list system and multiple feeds on the home screen.

**Additional context**
Since this system is exactly like the Twitter system, checking out how Twitter handles lists would help understand this feature request better.

**Comment by austinhuang0131** [comment] 2021-06-16 14:27
Duplicate of #328

**Closed by austinhuang0131** 2021-06-16 14:27 UTC
Labels: enhancement
