### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FOSS-Love** [austinhuang0131/barinsta#1640] opened 2021-07-13 05:11 UTC
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq.html).

## Steps

1. Open any profile.
2. Select suggested users tab.
3. See error.

## Environment

 - Device: Realme 6
 - Android version: 10

## Additional info

```
Error report collected on: 2021-07-13T07:10:30.426

Information:
==============
VERSION		    : 19.2.4-github_release
VERSION_CODE	: 65
PHONE-MODEL	    : RMX2001
ANDROID_VERS	: 10
ANDROID_REL	    : 29
BRAND			: realme
MANUFACTURER	: realme
BOARD			: oppo6785
DEVICE			: RMX2001L1
PRODUCT		    : RMX2001
HOST			: ubuntu-142-12
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Parameter specified as non-null is null: method awais.instagrabber.repositories.responses.notification.Notification.<init>, parameter pk
	at awais.instagrabber.repositories.responses.notification.Notification.<init>(Unknown Source:7)
	at awais.instagrabber.webservices.-$$Lambda$NewsService$4$y4gNFoXf9vKoA4UUFom1_DdrH2o.apply(lambda:8)
	at j$.util.stream.L2$d$a.accept(Unknown Source:6)
	at j$.util.Iterator$-CC.$default$forEachRemaining(:2)
	at j$.util.Iterator$-EL.forEachRemaining(Unknown Source:10)
	at j$.util.s$i.forEachRemaining(Unknown Source:24)
	at j$.util.stream.x1.c0(:4)
	at j$.util.stream.J2.d(:2)
	at j$.util.stream.x1.m0(:2)
	at j$.util.stream.L2.collect(:3)
	at awais.instagrabber.webservices.NewsService$4.onResponse(NewsService.java:7)
	at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(lambda:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

```

**Comment by ammargitham** [comment] 2021-07-13 11:52
Duplicate of #1450

**Closed by ammargitham** 2021-07-13 11:52 UTC
Labels: bug
