### ISSUE TITLE
[BUG] Empty space for anonymous profile

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1058] opened 2021-04-12 10:58 UTC
(I believe this is not duplicate of #1035, because this is about _after_ logging out there's empty space left, while #1035 was talking about showing the placeholder while still logged in.)

![20210412_125440](https://user-images.githubusercontent.com/35201200/114384046-84c38700-9b8e-11eb-9b1c-850854f2657b.jpg)
Show a generic profile icon and "Not logged in" text

**Comment by austinhuang0131** [comment] 2021-04-17 21:34
Duplicate of #1035

**Closed by austinhuang0131** 2021-04-17 21:34 UTC
Labels: enhancement
