### ISSUE TITLE
[BUG] Custom emoji reactions won't work

### ISSUE THREAD

**Issue by AlmightyWings232** [austinhuang0131/barinsta#1278] opened 2021-05-18 13:11 UTC
I can't react with any custom emojis outside of the default selection of ❤️, 😂, 😢, 😠, 👍 in DMs. Essentially + button when reacting doesn't work, it doesn't even bring up a menu. I attached a video showing the bug as well.

## Environment

 - Device: Honor Play (COR-L29)
 - Android version: 9 (EMUI Version 9.1.0)
 
https://user-images.githubusercontent.com/44907494/118656256-456a0500-b7e2-11eb-843f-bb719f1a9801.mp4

**Comment by AlmightyWings232** [comment] 2021-05-18 13:13
Adding this in now because I forgot when posting the issue, but I'm on the latest version - 19.2.1-github_release (62)

**Comment by ammargitham** [comment] 2021-05-18 13:54
Duplicate of #1137

**Closed by ammargitham** 2021-05-18 13:54 UTC
Labels: bug

**Comment by AlmightyWings232** [comment] 2021-05-18 14:03
Aaah, right. I didn't notice it was already reported, my bad
