### ISSUE TITLE
Messages in realtime

### ISSUE THREAD

**Issue by Androz2091** [austinhuang0131/barinsta#1623] opened 2021-07-11 12:57 UTC
I need to refresh every 5-6 seconds to get the latest messages. It's very painful because when discussing we dont always have the time to refresh then write our message then send it then refresh etc.
Is there any way to get the messages in real-time? Thank you

**Comment by austinhuang0131** [comment] 2021-07-11 13:33
Duplicate of #119

**Closed by austinhuang0131** 2021-07-11 13:33 UTC
