### ISSUE TITLE
[BUG] Posts doubling when update feed on v19.x

### ISSUE THREAD

**Issue by RickyM7** [austinhuang0131/barinsta#256] opened 2020-11-07 19:23 UTC
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

When I pull to update the feed the posts are doubling endlessly.

## Step

1. Go to 'Feed'
2. Pull to update feed
3. See error

## Environment

 - Device: Xiaomi Redmi Note 4
 - Android version: Miui 11 - 7.0

## Additional info
~~This still continues on v19.0.5.~~
Fixed in v19.1.0.

**Comment by RickyM7** [comment] 2020-11-07 22:01
@austinhuang0131 I just realized that this bug does not occur in this Layout Style:
![List Layout](https://user-images.githubusercontent.com/24703825/98452110-2b60b300-212b-11eb-8514-db4285316adb.jpg)
In the other 2 Layout Styles the bug occurs.

**Comment by austinhuang0131** [comment] 2020-11-07 22:08
yeah but i'm using the first one and this issue doesn't seem to be there

**Comment by RickyM7** [comment] 2020-11-07 22:16
Strange, I've tested several layout variations and the bug always occurs, maybe it's related to my slow connection, or maybe it's some bug in the webview. Anyway I'll talk if I notice anything else

**Comment by austinhuang0131** [comment] 2020-11-07 22:19
imo it's very possible that this is due to connection (also webview is like the browser, not backend requests)

refer to https://github.com/austinhuang0131/barinsta/commit/e32002fac8aad3b88b509dd6c5c444d2cc20f35a if you'd like

**Comment by RickyM7** [comment] 2020-11-07 22:34
If the bug is in the app, then it's in the "Column count" part, that was the only part that changed something in the bug. With the "Column count" option in "2" the posts are repeated 4 times before returning to normal and when the "Column count" option is in "3" the posts are repeated 8 times before returning to normal

**Comment by austinhuang0131** [comment] 2020-11-07 22:41
You said you pulled to refresh... I assume it's pulling the refresh bubble down. It should clear all posts then feed new posts from page 1.

For next pages: Once you reached the end of all (existing) posts, it'll refresh. And if you try to hit it during refresh, they'll be ignored.

**Comment by RickyM7** [comment] 2020-11-07 23:04
> You said you pulled to refresh... I assume it's pulling the refresh bubble down.

Exactly. Incidentally, this bug only occurs in the Feed tab.

**Comment by ammargitham** [comment] 2020-11-17 09:42
If you are still experiencing this, try to give more info regarding what was the network status at that moment or any other thing which may be relevant. As of now, I cannot reproduce this.

**Comment by RickyM7** [comment] 2020-11-17 15:13
@ammargitham It's just that I think this bug only occurs when you have few things in the feed, something between 2 or 3 posts, after all when it comes to a certain number of repetitions the feed goes back to normal and it occurs regardless of whether my connection is slow or fast.

**Comment by austinhuang0131** [comment] 2020-12-19 21:56
closing unless new info pops up

**Comment by RickyM7** [comment] 2020-12-19 22:46
All the information I got about this bug:
- This bug only occurs in the "Feed" tab.
- This bug does not occur in the list layout.
- This bug only occurs if you have very few items in the feed (10 posts or less).

I can currently only reproduce this bug if I force a lot to update the page. My verdict is that this bug is caused by my internet connection and that this issue can be kept closed.

**Comment by RickyM7** [comment] 2020-12-23 13:56
Just for information, this bug continues on v19.0.3 and I noticed that it occurs also in the saved posts part.

**Comment by austinhuang0131** [comment] 2020-12-23 14:06
actually "very few items" could be a problem but like I would need an account

**Comment by ammargitham** [comment] 2021-04-03 14:34
Is this still occurring?

**Comment by RickyM7** [comment] 2021-04-03 14:56
> Is this still occurring?

Apparently yes, but it's hard to make it occur because the send message button changes to the voice message button as soon as we click to send any message. Maybe this issue can be closed.

**Comment by RickyM7** [comment] 2021-04-03 14:59
> Is this still occurring?

Sorry, I ended up getting in the way of the previous comment. And no, this bug is no longer occurring. I'm sorry I haven't tested this before.

**Closed** 2021-04-03 15:04 UTC
Labels: ??????, bug
