### ISSUE TITLE
[BUG] Crash report: Suggested users

### ISSUE THREAD

**Issue by ikanakova** [austinhuang0131/barinsta#1585] opened 2021-07-07 05:43 UTC
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-07T07:39:34.486

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: Nokia 6.1
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: Nokia
MANUFACTURER	: HMD Global
BOARD			: SDM630
DEVICE			: PL2_sprout
PRODUCT		: Plate2_00WW
HOST			: cm-build-42-110-5050
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Parameter specified as non-null is null: method awais.instagrabber.repositories.responses.notification.Notification.<init>, parameter pk
	at awais.instagrabber.repositories.responses.notification.Notification.<init>(Unknown Source:7)
	at awais.instagrabber.webservices.-$$Lambda$NewsService$3$FntosWUGW1rtAaHZh3Z1PjXgIdQ.apply(lambda:10)
	at j$.util.stream.L2$d$a.accept(Unknown Source:6)
	at j$.util.Iterator$-CC.$default$forEachRemaining(:2)
	at j$.util.Iterator$-EL.forEachRemaining(Unknown Source:10)
	at j$.util.s$i.forEachRemaining(Unknown Source:24)
	at j$.util.stream.x1.e0(:4)
	at j$.util.stream.J2.d(:2)
	at j$.util.stream.x1.o0(:2)
	at j$.util.stream.L2.collect(:3)
	at awais.instagrabber.webservices.NewsService$3.onResponse(NewsService.java:11)
	at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(lambda:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Cause:
==============

**** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-07-07 12:11
Duplicate of #1450

**Closed by austinhuang0131** 2021-07-07 12:11 UTC
Labels: bug
