### ISSUE TITLE
[BUG] Crash report

### ISSUE THREAD

**Issue by neekless** [austinhuang0131/barinsta#1603] opened 2021-07-09 03:11 UTC
New Trace collected: 
===================== 
IMPORTANT: If sending by email, your email address and the entire content will be made public at 
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues 
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation. 
 
Error report collected on: 2021-07-09T10:38:33.473 
 
Information: 
============== 
VERSION  : 19.2.3-fdroid 
VERSION_CODE : 64 
PHONE-MODEL : Pixel 2 XL 
ANDROID_VERS : 11 
ANDROID_REL : 30 
BRAND   : google 
MANUFACTURER : Google 
BOARD   : taimen 
DEVICE   : taimen 
PRODUCT  : taimen 
HOST   : arter97-paserv 
TAGS   : release-keys 
 
Stack: 
============== 
java.lang.NullPointerException: Parameter specified as non-null is null: method awais.instagrabber.repositories.responses.notification.Notification.<init>, parameter pk 
 at awais.instagrabber.repositories.responses.notification.Notification.<init>(Unknown Source:7) 
 at awais.instagrabber.webservices.-$$Lambda$NewsService$3$FntosWUGW1rtAaHZh3Z1PjXgIdQ.apply(lambda:10) 
 at j$.util.stream.L2$d$a.accept(Unknown Source:6) 
 at j$.util.Iterator$-CC.$default$forEachRemaining(:2) 
 at j$.util.Iterator$-EL.forEachRemaining(Unknown Source:10) 
 at j$.util.s$i.forEachRemaining(Unknown Source:24) 
 at j$.util.stream.x1.e0(:4) 
 at j$.util.stream.J2.d(:2) 
 at j$.util.stream.x1.o0(:2) 
 at j$.util.stream.L2.collect(:3) 
 at awais.instagrabber.webservices.NewsService$3.onResponse(NewsService.java:11) 
 at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(lambda:3) 
 at android.os.Handler.handleCallback(Handler.java:938) 
 at android.os.Handler.dispatchMessage(Handler.java:99) 
 at android.os.Looper.loop(Looper.java:223) 
 at android.app.ActivityThread.main(ActivityThread.java:7664) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
 
Cause: 
============== 
Go to More > Suggested users > crash. Logged in. 
 
**** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-07-09 04:27
Duplicate of #1450

**Closed by austinhuang0131** 2021-07-09 04:27 UTC
Labels: bug
