### ISSUE TITLE
Crash caused by setting downloads folder  

### ISSUE THREAD

**Issue by n-xlkt** [austinhuang0131/barinsta#1590] opened 2021-07-07 23:28 UTC
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at
IMPORTANT: https://github.com/austinhuang0131/barinsta/issues
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-07T19:26:52.489

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: Pixel XL
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: google
MANUFACTURER	: Google
BOARD			: marlin
DEVICE			: marlin
PRODUCT		: marlin
HOST			: fb6307c88a73
TAGS			: dev-keys

Stack:
==============
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5168)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at awais.instagrabber.activities.-$$Lambda$DirectorySelectActivity$0hRDDTqoiGGyn-qTGVeQdFzORJU.onClick(lambda:3)
	at android.view.View.performClick(View.java:7259)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

Cause:
==============

**** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-07-07 23:31
Duplicate of #1467 

Your device lacks DocumentsUI, which is included in the system's file manager. Please reenable it or reinstall it if you somehow uninstalled it by root.

**Closed by austinhuang0131** 2021-07-07 23:31 UTC
Labels: bug

**Comment by n-xlkt** [comment] 2021-07-07 23:49
why is this a critical bug that prevents all use? shouldn't I be able to refuse access and use the app as normal?

**Comment by austinhuang0131** [comment] 2021-07-07 23:53
You can just select an empty folder (in fact you're encouraged to select a new folder)? What's the point of refusing access?
