### ISSUE TITLE
[FTR] don't lock the screen while watching a video

### ISSUE THREAD

**Issue by datesastick** [austinhuang0131/barinsta#957] opened 2021-04-03 22:14 UTC
It happened to me a few times that I watched a IG video but suddenly my screen locked. 
It isn't comfortable to click on the screen every 20 seconds so the screen won't lock.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by austinhuang0131** [comment] 2021-04-03 22:15
Duplicate of #490

**Closed by austinhuang0131** 2021-04-03 22:15 UTC
Labels: enhancement
