### ISSUE TITLE
[FTR] Send Posts / stories to direct messages

### ISSUE THREAD

**Issue by yant0** [austinhuang0131/barinsta#1089] opened 2021-04-14 14:30 UTC
instagram have share button both in post and story to send those things to someone / your story ( i only need the forward to other people feature)

thanks for the app

**Comment by xbvrhlmb** [comment] 2021-04-15 09:41
Looks like already there #537

**Comment by austinhuang0131** [comment] 2021-04-15 13:06
Duplicate of #537

**Closed by austinhuang0131** 2021-04-15 13:06 UTC
Labels: enhancement
