### ISSUE TITLE
[FTR] Add "Favourites" button and timeline for non-logged-in's

### ISSUE THREAD

**Issue by EukalyptusX** [austinhuang0131/barinsta#499] opened 2021-01-01 13:59 UTC
Hi,

first I'd really like to thank you for your work. It's awesome!!
And secondly, I wish you a happy new year :)

I just have little questions or feature requests (maybe I'm just too stupid to find it xD).

1. To find the favourites as a non-logged-in user, I always have to go via "More" -> "Favourites". Would it be possible to add an icon at the bottom for favorites on the main view (just where " Profile" and "More" is listed)?
2. Is it / Would it be possible to see the timeline of all posts from all accounts that are marked as favourites? Instead of browsing through each account separately? Also as a non-logged-in user.

Thank you so much and have a great day!

Patrick

**Comment by austinhuang0131** [comment] 2021-04-02 17:20
1. Implemented by #850 
2. Duplicate of #24

**Closed by austinhuang0131** 2021-04-02 17:20 UTC
Labels: enhancement
