### ISSUE TITLE
[BUG] Username detection does not allow for periods

### ISSUE THREAD

**Issue by tfbninja** [austinhuang0131/barinsta#454] opened 2020-12-27 02:57 UTC
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

## Steps

1. Go to anywhere a username that has a period is displayed
2. You can see that only the part before the period is clickable
3. Clicking takes you to a profile of the username section before the period

## Environment

 - Device: Moto G6
 - Android version: 9

## Additional info

None

**Comment by austinhuang0131** [comment] 2020-12-27 03:15
Are you using F-Droid?

**Comment by tfbninja** [comment] 2020-12-27 03:22
Yes.

Dec 26, 2020 8:15:56 PM Austin Huang <notifications@github.com>:

**Comment by austinhuang0131** [comment] 2020-12-27 03:47
This has been fixed in v19.0.3 already. Please wait for F-Droid update (which should happen in the next few days).

Duplicate of #408

**Closed by austinhuang0131** 2020-12-27 03:47 UTC
Labels: bug
