### ISSUE TITLE
[FTR] Save to microsd card

### ISSUE THREAD

**Issue by Dialga** [austinhuang0131/barinsta#433] opened 2020-12-21 11:13 UTC
Hi developer, thanks for the great app!
Can support for saving to the sdcard be added? Currently if the internal storage is running out of space it would be convenient to save to external storage instead on the micro sd card or otg usb. Thanks

**Comment by austinhuang0131** [comment] 2020-12-21 14:07
Duplicate of #48

**Closed by austinhuang0131** 2020-12-21 14:07 UTC
Labels: enhancement
