### ISSUE TITLE
[BUG] No stories button anymore, lower quality images/videos download

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#683] opened 2021-02-12 13:25 UTC
Sadly, Barinsta is full of bugs. Now the Stories button doesn't appear at all. Also like [Anoop posted here](https://github.com/austinhuang0131/barinsta/issues/676) this app downloads lower quality versions of images/videos. This is a dealbreaker. I tried apps like Instander and those get the highest quality available and load the resources much faster. I gave up using Barinsta until this app is fixed.

- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Environment

 - Device: 
 - Android version:

**Comment by mmuenstedt** [comment] 2021-02-12 16:13
On my phone the stories are not shown either. The loading circle is constantly on the top of the app.
I also have the latest version on android 10.

**Comment by austinhuang0131** [comment] 2021-02-13 03:20
Duplicate of #681 and #686

**Closed by austinhuang0131** 2021-02-13 03:20 UTC
Labels: bug
