### ISSUE TITLE
[FTR] Allow bookmarking posts in anonymous mode

### ISSUE THREAD

**Issue by amanharwara** [austinhuang0131/barinsta#1115] opened 2021-04-17 06:36 UTC
**Describe the solution you'd like**
Currently you can only favourite a profile in anonymous mode. There should be a way for bookmarking posts in anonymous mode as well.

**Comment by austinhuang0131** [comment] 2021-04-17 13:29
Duplicate of #290

**Closed by austinhuang0131** 2021-04-17 13:29 UTC
Labels: enhancement
