### ISSUE TITLE
[BUG]  i am not able to see my chats in direct message tab.

### ISSUE THREAD

**Issue by Soul-Snatcher** [austinhuang0131/barinsta#669] opened 2021-02-06 13:02 UTC
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Environment

 - Device: 
 - Android version:

**Comment by austinhuang0131** [comment] 2021-02-07 02:03
Duplicate of #444

**Closed by austinhuang0131** 2021-02-07 02:03 UTC
Labels: bug
