### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by errvnd** [austinhuang0131/barinsta#1702] opened 2021-07-21 15:29 UTC
While selecting saved items, from profile.

## Environment

 - Device: Rmx2170
 - Android version: 10

New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at https://github.com/austinhuang0131/barinsta/issues.

When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-21T20:54:39.019

Information:
==============
VERSION	    : 19.2.4-github_release
VERSION_CODE	: 65
PHONE-MODEL	    : RMX2170
ANDROID_VERS	: 10
ANDROID_REL	    : 29
BRAND	: realme
MANUFACTURER	: realme
BOARD	: atoll
DEVICE	: RMX2170L1
PRODUCT	    : RMX2170
HOST	: Ubuntu-143-28
TAGS	: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
at awais.instagrabber.adapters.SavedCollectionsAdapter.onBindViewHolder(SavedCollectionsAdapter.java:12)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:164)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:60)
at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:25)
at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1845)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:843)
at android.view.View.layout(View.java:22760)
at android.view.ViewGroup.layout(ViewGroup.java:6410)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3511)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2927)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2029)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8391)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1097)
at android.view.Choreographer.doCallbacks(Choreographer.java:920)
at android.view.Choreographer.doFrame(Choreographer.java:846)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1082)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:228)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

*** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-07-22 13:20
Duplicate of #1688

**Closed by austinhuang0131** 2021-07-22 13:20 UTC
Labels: bug
