### ISSUE TITLE
[BUG] App crashes when clicking on "suggested Users" 

### ISSUE THREAD

**Issue by aashu** [austinhuang0131/barinsta#1591] opened 2021-07-08 07:50 UTC
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq.html).

## Steps
 Go to **more** tab and click on **Suggested Users**

## Trace
================

Error report collected on: 2021-07-07T20:23:20.746

Information:
==============
VERSION		: 19.2.3-fdroid
VERSION_CODE	: 64
PHONE-MODEL	: POCO M2 Pro
ANDROID_VERS	: 11
ANDROID_REL	: 30
BRAND			: POCO
MANUFACTURER	: Xiaomi
BOARD			: miatoll
DEVICE			: gram
PRODUCT		: havoc_miatoll
HOST			: Hyper-server3
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Parameter specified as non-null is null: method awais.instagrabber.repositories.responses.notification.Notification.<init>, parameter pk
	at awais.instagrabber.repositories.responses.notification.Notification.<init>(Unknown Source:7)
	at awais.instagrabber.webservices.-$$Lambda$NewsService$3$FntosWUGW1rtAaHZh3Z1PjXgIdQ.apply(lambda:10)
	at j$.util.stream.L2$d$a.accept(Unknown Source:6)
	at j$.util.Iterator$-CC.$default$forEachRemaining(:2)
	at j$.util.Iterator$-EL.forEachRemaining(Unknown Source:10)
	at j$.util.s$i.forEachRemaining(Unknown Source:24)
	at j$.util.stream.x1.e0(:4)
	at j$.util.stream.J2.d(:2)
	at j$.util.stream.x1.o0(:2)
	at j$.util.stream.L2.collect(:3)
	at awais.instagrabber.webservices.NewsService$3.onResponse(NewsService.java:11)
	at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(lambda:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Cause:
==============

**** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-07-08 14:15
Duplicate of #1450

**Closed by austinhuang0131** 2021-07-08 14:15 UTC
Labels: bug
