### ISSUE TITLE
[FTR]Follower tracker

### ISSUE THREAD

**Issue by vhateg** [austinhuang0131/barinsta#646] opened 2021-01-31 03:34 UTC
There are some sketchy apps on app stores that tell you the people that unfollowed your profile by saving a database of your followers when you close the app and then comparing it with the actual follower list when you open the app next time, effectively telling you the followers you've lost and the ones you've gained.
It may be cool if this was implemented in a free open-source app (such as Batinsta), that does not have weird limitations or scammy payments, like all the other apps do.

**Comment by austinhuang0131** [comment] 2021-01-31 03:39
Duplicate of #244

**Closed by austinhuang0131** 2021-01-31 03:39 UTC
Labels: enhancement
