### ISSUE TITLE
A dedicated feed option for favorited pages.

### ISSUE THREAD

**Issue by lijovklm** [austinhuang0131/barinsta#1718] opened 2021-07-22 13:12 UTC
Hey, thanks for making this excellent app.

I was thing of having a feed just as the regular feed, just for the favorited pages, individual accounts etc.
This should be present even in private mode as we can favorite channels without logging in.

**Describe the solution you'd like**
A feed of favorited pages, like the regular insta feed, may be sorted about most recent.

Please try to include this feature if possible. Thanks again.

**Comment by austinhuang0131** [comment] 2021-07-22 13:13
Duplicate of #24

**Closed by austinhuang0131** 2021-07-22 13:13 UTC
Labels: enhancement
