### ISSUE TITLE
[FTR] Favorites feed

### ISSUE THREAD

**Issue by modelfe** [austinhuang0131/barinsta#673] opened 2021-02-08 02:35 UTC
Would it be possible to implement a feed just for the accounts that have been favorited in the app? I was thinking it could function exactly the same as the usual Feed tab (with stories and posts), and could be accessed from the Favorites section in the More tab.

I have little in the way of coding skills, so am unable to help if this is a big ask.

Cheers

**Comment by austinhuang0131** [comment] 2021-02-08 03:23
Duplicate of #24

**Closed by austinhuang0131** 2021-02-08 03:23 UTC
Labels: enhancement
