### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BlueStarZero** [austinhuang0131/barinsta#1720] opened 2021-07-22 14:24 UTC
- [Yes] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [Yes] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq.html).

BUG DESCRIPTION:
App crashes everytime I tap the Saved Posts button on my profile.
App Version: 19.2.4-fdroid (65)

## Environment

 - Device: OnePlus 5T
 - Android version: 10

## Additional info

CRASH DUMP:

New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at https://github.com/austinhuang0131/barinsta/issues.

When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-22T10:18:37.866

Information:
==============
VERSION		    : 19.2.4-fdroid
VERSION_CODE	: 65
PHONE-MODEL	    : ONEPLUS A5010
ANDROID_VERS	: 10
ANDROID_REL	    : 29
BRAND			: OnePlus
MANUFACTURER	: OnePlus
BOARD			: msm8998
DEVICE			: OnePlus5T
PRODUCT		    : OnePlus5T
HOST			: rd-build-105
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
	at awais.instagrabber.adapters.SavedCollectionsAdapter.onBindViewHolder(SavedCollectionsAdapter.java:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:164)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:60)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:25)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2834)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8048)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
	at android.view.Choreographer.doFrame(Choreographer.java:902)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

*** End of current Report ***
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at https://github.com/austinhuang0131/barinsta/issues.

When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-22T10:17:20.750

Information:
==============
VERSION		    : 19.2.4-fdroid
VERSION_CODE	: 65
PHONE-MODEL	    : ONEPLUS A5010
ANDROID_VERS	: 10
ANDROID_REL	    : 29
BRAND			: OnePlus
MANUFACTURER	: OnePlus
BOARD			: msm8998
DEVICE			: OnePlus5T
PRODUCT		    : OnePlus5T
HOST			: rd-build-105
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
	at awais.instagrabber.adapters.SavedCollectionsAdapter.onBindViewHolder(SavedCollectionsAdapter.java:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:164)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:60)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:25)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2834)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8048)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
	at android.view.Choreographer.doFrame(Choreographer.java:902)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

*** End of current Report ***
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at https://github.com/austinhuang0131/barinsta/issues.

When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2021-07-22T10:17:33.662

Information:
==============
VERSION		    : 19.2.4-fdroid
VERSION_CODE	: 65
PHONE-MODEL	    : ONEPLUS A5010
ANDROID_VERS	: 10
ANDROID_REL	    : 29
BRAND			: OnePlus
MANUFACTURER	: OnePlus
BOARD			: msm8998
DEVICE			: OnePlus5T
PRODUCT		    : OnePlus5T
HOST			: rd-build-105
TAGS			: release-keys

Stack:
==============
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
	at awais.instagrabber.adapters.SavedCollectionsAdapter.onBindViewHolder(SavedCollectionsAdapter.java:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:164)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:60)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:25)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2834)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8048)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
	at android.view.Choreographer.doFrame(Choreographer.java:902)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

*** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-07-22 14:42
Duplicate of #1688

**Closed by austinhuang0131** 2021-07-22 14:42 UTC
Labels: bug
