### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#264] opened 2020-11-09 20:50 UTC
1. The saved pictures don't have the extension. It misses a dot. e.g. filejpg instead of file.jpg Sometimes it works correctly.

2. Sometimes I get StoryViewerFragment as title at the Story view.

3. I get -1 at likes by default and 0 after I like a post. Perhaps the proper likes count is not retrieved.

4. I get a notification per download and it clogs the notification bar. Wouldn't it better to group them together? Also a toast message to confirm download would be great.

5. The app is more sluggish than before, perhaps because of the animations. Could you add an option to turn off animations? **Also that short flash before items being displayed is VERY annoying.** Please remove it or add an option to disable it.

6. At the profile pages, the header with profile info, followers, following, etc. is stuck for too long while scrolling down. Make it disappear quicker because it stays in the way and I must scroll down too much and miss the first posts.

7. The image zoom after I tap a post is buggy. It seems to try to zoom twice, the first time is cancelled quickly and that leads to a very annoying flickering.

- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

## Environment

 - Device: Samsung Galaxy A50
 - Android version: 10

**Comment by austinhuang0131** [comment] 2020-11-13 16:59
Can't reproduce 1, 3 and 7. Will fix 2.

I thought 5 is an emulator-only issue...

For 4 I'm pretty sure those are grouped together (Android 9) when the entire downloading queue is cleared.

Guess Android 10 is weird...

**Comment by ammargitham** [comment] 2020-11-14 08:29
1. ~~The saved pictures don't have the extension. It misses a dot. e.g. filejpg instead of file.jpg Sometimes it works correctly.~~ 
  Fixed

2. ~~Sometimes I get StoryViewerFragment as title at the Story view.~~
  Fixed

3. I get -1 at likes by default and 0 after I like a post. Perhaps the proper likes count is not retrieved.
  Cannot reproduce. If possible provide a link to the post where you noticed this.

4. I get a notification per download and it clogs the notification bar. Wouldn't it better to group them together? Also a toast message to confirm download would be great.
  Downloads initiated in a single request are grouped together. I'll check the possibility to enhance this so that future downloads are also grouped in the initial group.

5. The app is more sluggish than before, perhaps because of the animations. Could you add an option to turn off animations? **Also that short flash before items being displayed is VERY annoying.** Please remove it or add an option to disable it.
  Cannot reproduce any flash. If possible send a screen recording? I don't notice much delay on my One Plus 3. Anyway, I can add an option to disable animations when opening a post. Other places are default animations provided in the android framework.

6. At the profile pages, the header with profile info, followers, following, etc. is stuck for too long while scrolling down. Make it disappear quicker because it stays in the way and I must scroll down too much and miss the first posts.
  Will look into it.

7. The image zoom after I tap a post is buggy. It seems to try to zoom twice, the first time is cancelled quickly and that leads to a very annoying flickering.
  Can't reproduce. Again, a screen recording will be helpful.

**Comment by alin-1** [comment] 2020-11-14 15:12
Regarding #7: I recorded a video with that annoying flickering when opening posts: https://streamable.com/q8jjbe

That double zoom is very noticeable.

**Comment by ammargitham** [comment] 2020-11-14 15:26
Interesting. This behavior doesn't happen with my device. Could be Samsung issue? Well, until I figure it out, you can disable the animation in the next version.

**Comment by alin-1** [comment] 2020-11-14 15:29
I uploaded 3 videos for the issues 5, 6 and 7.

Issue #5: the annoying white flash before an item is displayed (e.g. Stories): https://streamable.com/n0lxqf

Issue #6: the stuck header that refuses to hide quickly: https://streamable.com/8urme2

Issue #7: the double zoom that causes annoying flickering when opening a post: https://streamable.com/kk8nj5

**Comment by alin-1** [comment] 2020-11-14 15:33
@ammargitham: I reduced the speed animations to .5x system wide from the Developer Options.

By the way, I posted 2 more videos about the issues 5 and 6.

**Comment by ammargitham** [comment] 2020-11-14 15:34
> 
> 
> @ammargitham: I reduced the speed animations to .5x system wide from the Developer Options.
> 
> By the way, I posted 2 more videos about the issues 5 and 6.

Can you try setting the speed back to normal to see if it helps?

**Comment by ammargitham** [comment] 2020-11-14 15:44
> Having an option to disable animations would be excellent. There are people with epilepsy (not me) and sensibility to flickering.

As I mentioned in one of the previous comments, the option to disable animation will be there in the next version. And I consider this a bug which needs to be fixed. The problem is that no one has mentioned this in the telegram group too which makes me think this is a device/manufacturer specific issue.

**Comment by austinhuang0131** [comment] 2020-11-14 15:59
I actually have this issue too, but only on emulators (since I run it with little RAM on my potato MacBook Air)

**Comment by ammargitham** [comment] 2020-11-14 16:02
Okay, will test it out on an emulator.

**Comment by alin-1** [comment] 2020-11-14 17:34
@ammargitham With the animation speed back to 1x and even with the Developer Options disabled, that bug is still there. So, it's either a bug in Barinsta or there is something wrong with the Samsung version of Android / the device itself.

**Comment by alin-1** [comment] 2020-11-14 17:53
@ammargitham With the animation speed back to 1x and even with the Developer Options disabled, that bug is still there.

I installed the latest version of Barinsta on Bluestacks (Android emulator for Windows based on an older Android version). I screen-recorded it and analyzed frame by frame that animation: no trace of issue #7. 

Most likely the Barinsta code is clashing with Android 10 (in general or the Samsung variety or just for this device) in some unexpected ways.

**Comment by ammargitham** [comment] 2020-11-15 09:40
Okay, I can reproduce #7 in my emulator. Looking into it.

**Comment by ammargitham** [comment] 2020-11-15 12:49
#7 should be fixed in https://github.com/ammargitham/barinsta/commit/fececb5fd24c3948548b43a3b79e2105b70ae8bc

**Comment by alin-1** [comment] 2020-11-15 13:58
@ammargitham: You're right.

**Closed** 2020-12-20 03:06 UTC
Labels: bug, compatibility
