### ISSUE TITLE
Download using Instagrabber fails with image corrupting downloaded images

### ISSUE THREAD

**Issue by ranjit0829** [austinhuang0131/barinsta#254] opened 2020-11-07 10:43 UTC
- [**YES**] My app is on the latest version. I understand that any other version is not supported.
- [ **YES**] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

## Steps
Go to  and try to 
1. Go to any profile in Instagrabber
2. Click on download images using **Current** or **Whole Album** option
3. Scroll down to '....' N/A
4. See error: see images

## Environment

 - Device: MI 8 SE
 - Android version: MIUI 12.0.2

## Additional info

Please See screen shots below:
After download: https://drive.google.com/file/d/1c6xjtX7tgjTKyWLZY_md8-6YLoM4r0cX/view?usp=sharing 
After opening image: https://drive.google.com/file/d/1vBrqKHbLfVCsz1tmpeF2zuvJHOYwHvNL/view?usp=sharing

Please help!

Thank you!

Ranjit

**Comment by ammargitham** [comment] 2020-11-07 10:54
Duplicate of #235

**Closed by ammargitham** 2020-11-07 10:54 UTC
Labels: bug
