### ISSUE TITLE
[BUG]  Discover show only "For you"

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#1187] opened 2021-04-30 10:28 UTC
Maybe the instagram disable other, but earlier i see other category "Eat" "Design" and other..
 
## Steps
1. Open App
2. Go to tab Discover
3. See only "For you"

## Environment
 - App version 19.2.1 github_release (62)
 - Android version:  5.1

**Comment by austinhuang0131** [comment] 2021-04-30 15:03
Duplicate of #1172

**Closed by austinhuang0131** 2021-04-30 15:03 UTC
Labels: bug
