### ISSUE TITLE
Missing direct download via sharing

### ISSUE THREAD

**Issue by derheiko** [austinhuang0131/barinsta#1406] opened 2021-06-07 13:24 UTC
Hello, since version 19.2.2 you can no longer select a direct download from the original Instagarm app via share. This is no longer displayed. Here is a screenshot from version 19.2.1 where it still works.

![Screenshot_2021-06-07-15-17-31-204_android~01~01-picsay](https://user-images.githubusercontent.com/61577407/121024372-736cb480-c7a4-11eb-9902-f112b607252e.jpg)

**Comment by austinhuang0131** [comment] 2021-06-07 13:26
Duplicate of #1325

**Closed by austinhuang0131** 2021-06-07 13:26 UTC
