### ISSUE TITLE
[BUG] while playing videos app get crashed

### ISSUE THREAD

**Issue by bloatware99** [austinhuang0131/barinsta#1365] opened 2021-05-30 17:24 UTC
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Environment

 - Device: motorola one power
 - Android version: 10

## Additional info

New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Sun May 30 22:36:17 GMT+05:30 2021

Information:
==============
VERSION		: 19.2.1-fdroid
VERSION_CODE	: 62
PHONE-MODEL	: motorola one power
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: motorola
MANUFACTURER	: motorola
BOARD			: sdm660
DEVICE			: chef_sprout
PRODUCT		: chef
HOST			: ilclbld86
TAGS			: release-keys

Stack:
==============
java.lang.IllegalStateException: valueFrom(0.0) must be smaller than valueTo(-9.223372E18)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:35)
	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:2)
	at android.view.View.draw(View.java:21482)
	at android.view.View.updateDisplayListIfDirty(View.java:20359)
	at android.view.View.draw(View.java:21214)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
	at android.view.View.draw(View.java:21485)
	at android.view.View.updateDisplayListIfDirty(View.java:20359)
	at android.view.View.draw(View.java:21214)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
	at android.view.View.draw(View.java:21485)
	at android.view.View.updateDisplayListIfDirty(View.java:20359)
	at android.view.View.draw(View.java:21214)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
	at android.view.View.updateDisplayListIfDirty(View.java:20350)
	at android.view.View.draw(View.java:21214)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
	at android.view.View.updateDisplayListIfDirty(View.java:20350)
	at android.view.View.draw(View.java:21214)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
	at android.view.View.draw(View.java:21485)
	at com.android.internal.policy.DecorView.draw(DecorView.java:815)
	at android.view.View.updateDisplayListIfDirty(View.java:20359)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3645)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3453)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2783)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1749)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7692)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

Cause:
==============

**** End of current Report ***
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Fri May 21 19:06:45 GMT+05:30 2021

Information:
==============
VERSION		: 19.2.1-fdroid
VERSION_CODE	: 62
PHONE-MODEL	: motorola one power
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: motorola
MANUFACTURER	: motorola
BOARD			: sdm660
DEVICE			: chef_sprout
PRODUCT		: chef
HOST			: ilclbld86
TAGS			: release-keys

Stack:
==============
java.lang.IllegalStateException: valueFrom(0.0) must be smaller than valueTo(0.0)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:35)
	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:2)
	at android.view.View.draw(View.java:21482)
	at android.view.View.updateDisplayListIfDirty(View.java:20359)
	at android.view.View.draw(View.java:21214)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4152)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
	at android.view.View.draw(View.java:21485)
	at android.view.View.updateDisplayListIfDirty(View.java:20359)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:20319)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:20319)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:20319)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:20319)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3645)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3453)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2783)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1749)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7692)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

Cause:
==============

**** End of current Report ***
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public on GitHub issues.
IMPORTANT: When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: Fri May 21 21:30:25 GMT+05:30 2021

Information:
==============
VERSION		: 19.2.1-fdroid
VERSION_CODE	: 62
PHONE-MODEL	: motorola one power
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: motorola
MANUFACTURER	: motorola
BOARD			: sdm660
DEVICE			: chef_sprout
PRODUCT		: chef
HOST			: ilclbld86
TAGS			: release-keys

Stack:
==============
java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore(Fragment.java:6)
	at androidx.lifecycle.ViewModelProvider.<init>(ViewModelProvider.java:1)
	at awais.instagrabber.customviews.PostsRecyclerView.init(PostsRecyclerView.java:22)
	at awais.instagrabber.fragments.HashTagFragment.access$1200(HashTagFragment.java:13)
	at awais.instagrabber.fragments.HashTagFragment$5.onSuccess(HashTagFragment.java:6)
	at awais.instagrabber.webservices.TagsService$1.onResponse(TagsService.java:3)
	at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(lambda:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

Cause:
==============

**** End of current Report ***

**Comment by austinhuang0131** [comment] 2021-05-30 17:42
Duplicate of #337

**Closed by austinhuang0131** 2021-05-30 17:42 UTC
Labels: bug
