### ISSUE TITLE
[FTR] Disable swipe up/down to close picture + disable text pop-up

### ISSUE THREAD

**Issue by Krystofido** [austinhuang0131/barinsta#760] opened 2021-03-04 20:10 UTC
**Is your feature request related to a problem? Please describe.**
1. Swipe up/down: To cite a meme, the amount of unwanted closing of pictures is too damn high. Whenever i try to zoom in to a picture or want to see the next picture of a multi-picure post, about 80% of times I'm accidently closing the picture. That's really frustrating.
2. Text pop-up. In the old look the text of a post was below the picture. Now the text is hovering transparently above the picture. Personally most of the times I absolutely don't care about the description and closing it on every single post just to see the whole thing is quite annoying.
3. The old version was able to switch to the next/previous post by just swiping right/left. That was an extremely helpful feature, it would be great if it could return in some form.

**Describe the solution you'd like**
1. Make it possible to turn off this functionality (I'm always just using the virtual keys) or at least some kind of lowering the sensitivity to an up/down swipe.
2. Also an option in the settings to turn off the default show-up of the description.
3. Some people might have found this feature annoying, so also let it be turned on/off in the settings? It would be really geat!

**Comment by austinhuang0131** [comment] 2021-03-04 20:17
1. Duplicate of #481 which is temporarily resolved on [v19.1.0-a1](https://github.com/austinhuang0131/barinsta/releases/tag/test-v19.1.0-a1).
2. Added in #609 and is available on v19.1.0-a1.
3. There are certain technical limitations, we might get to it some day, but probably not in the near future.

**Comment by Krystofido** [comment] 2021-03-04 21:19
Well, in that case sorry for kind of spamming unnecessarily duplicate issues and thanks for the quick reply! I guess v19.1.0-a1 is only available here, not on F-Droid, right? Have a nice day!

**Comment by austinhuang0131** [comment] 2021-03-04 23:03
Yeah, it's non-prod so it's not on F-Droid. But it'll get to production soon.

**Closed by austinhuang0131** 2021-03-04 23:03 UTC
Labels: enhancement
